configuration:
  bootstrapServers : localhost:9092
  groupId : car
  enableAutoCommit : true
  autoCommitIntervalMs : 1000
  sessionTimeoutMs : 30000
  keyDeserializer : org.apache.kafka.common.serialization.StringDeserializer
  valueDeserializer : org.apache.kafka.common.serialization.StringDeserializer
